### Model — load CPT checkpoint as base, then SFT on top
model_name_or_path: /scratch/$USER/huggingface_cache/hub/models--meta-llama--Meta-Llama-3.1-8B/snapshots/d04e592bb4f6aa9cfee91e2e20afa771667e1d4b
adapter_name_or_path: /scratch/$USER/foodmole_workspace/checkpoints/llama3-8b-cpt/checkpoint-22953

### Method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 64
lora_alpha: 128
lora_target: all

### Dataset
dataset_dir: /home/svu/$USER/foodmole/configs
dataset: foodmole_sft
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 8

### Output
output_dir: /scratch/$USER/foodmole_workspace/checkpoints/llama3-8b-cpt-sft-lora-foodmole
logging_dir: /scratch/$USER/foodmole_workspace/logs/llama3-8b-cpt-sft-lora-foodmole
logging_steps: 50
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### Train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
